---

  - name: Copy shell script to remote server
    copy:
        src: install_portworx.sh
        dest: /opt/install_portworx.sh
        mode: a+x

  - name: Run installation script
    shell:  /opt/install_portworx.sh {{ cluster_name }} {{ consul_ip }} {{ dev }} {{ dev1 }} {{ drive }} 
